apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    cloud.google.com/neg-status: '{"network_endpoint_groups":{"5004":"k8s1-ad716a6e-default-match-service-5004-ef4994cd"},"zones":["asia-southeast1-a"]}'
  creationTimestamp: "2021-11-09T22:19:36Z"
  labels:
    app: match
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":5004,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2021-11-09T22:19:36Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:cloud.google.com/neg-status: {}
    manager: glbc
    operation: Update
    time: "2021-11-09T23:20:14Z"
  name: match-service
  namespace: default
  resourceVersion: "82735"
  uid: dc0e969c-d828-46eb-947b-4d02688ac4a4
spec:
  clusterIP: 10.40.4.31
  clusterIPs:
  - 10.40.4.31
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31616
    port: 5004
    protocol: TCP
    targetPort: 5004
  selector:
    app: match
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
