apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: messagehpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: message
  minReplicas: 1
  maxReplicas: 3