apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: editorhpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: editor
  minReplicas: 1
  maxReplicas: 3