apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    cloud.google.com/neg-status: '{"network_endpoint_groups":{"5003":"k8s1-ad716a6e-default-editor-service-5003-1719d9f2"},"zones":["asia-southeast1-a"]}'
  creationTimestamp: "2021-11-09T22:20:59Z"
  labels:
    app: editor
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":5003,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2021-11-09T22:20:59Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:cloud.google.com/neg-status: {}
    manager: glbc
    operation: Update
    time: "2021-11-09T23:20:15Z"
  name: editor-service
  namespace: default
  resourceVersion: "82737"
  uid: 06ad8785-1d83-46ed-8438-26aa839fc3b3
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31022
    port: 5003
    protocol: TCP
    targetPort: 5003
  selector:
    app: editor
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
