apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: matchhpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: match
  minReplicas: 1
  maxReplicas: 3