# cloudbuild.yaml

steps:
### Build & Deploy Frontend

# SERVICE_NAME = web
# IMAGE_NAME = web

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cs3219-team23-328712/web:$COMMIT_SHA', './frontend']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cs3219-team23-328712/web:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'web', '--image', 'gcr.io/cs3219-team23-328712/web:$COMMIT_SHA', '--region', 'asia-east1']
images:
- gcr.io/cs3219-team23-328712/web:$COMMIT_SHA
options:
  logging: CLOUD_LOGGING_ONLY