# cloudbuild.yaml for Helm Deployment
timeout: 2000s
steps:

##################### Question #########################
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cs3219-team23-328712/question', './backend/questions']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cs3219-team23-328712/question']


##################### Web #########################
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cs3219-team23-328712/web', './frontend']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cs3219-team23-328712/web']

##################### Helm Deployment #########################
# Configure kubernetes
- name: gcr.io/cloud-builders/kubectl
  id: Configure kubectl
  args:
    - cluster-info
  env:
    - CLOUDSDK_COMPUTE_REGION=asia-southeast1-a
    - CLOUDSDK_CONTAINER_CLUSTER=peerup-cluster
    - KUBECONFIG=/workspace/.kube/config

#Uninstall with Helm
- name: gcr.io/cs3219-team23-328712/helm
  args: ['uninstall', 'peerprep']
  env:
    - KUBECONFIG=/workspace/.kube/config
    - TILLERLESS=false
    - TILLER_NAMESPACE=kube-system

# Delete all svc in kubectl
- name: gcr.io/cloud-builders/kubectl
  args: ['delete', 'svc', '--all']
  env:
    - CLOUDSDK_COMPUTE_REGION=asia-southeast1-a
    - CLOUDSDK_CONTAINER_CLUSTER=peerup-cluster
    - KUBECONFIG=/workspace/.kube/config


#Deploy with Helm
- name: gcr.io/cs3219-team23-328712/helm
  args: ['install', 'peerprep', './helm-deployment']
  env:
    - KUBECONFIG=/workspace/.kube/config
    - TILLERLESS=false
    - TILLER_NAMESPACE=kube-system

images:
- gcr.io/cs3219-team23-328712/question
- gcr.io/cs3219-team23-328712/web

options:
  logging: CLOUD_LOGGING_ONLY
