# cloudbuild.yaml

steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['cd', '/backend/users/', "&&", 'build', '-t', 'gcr.io/cs3219-team23-328712/users:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cs3219-team23-328712/users:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'users', '--image', 'gcr.io/cs3219-team23-328712/users:$COMMIT_SHA', '--region', 'asia-east1']
images:
- gcr.io/cs3219-team23-328712/users:$COMMIT_SHA