# cloudbuild.yaml

steps:
### Build & Deploy Match Microservice

# SERVICE_NAME = match
# IMAGE_NAME = match

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cs3219-team23-328712/match:$COMMIT_SHA', './backend/match']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cs3219-team23-328712/match:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'match', '--image', 'gcr.io/cs3219-team23-328712/match:$COMMIT_SHA', '--region', 'asia-east1']
# Configure a kubectl workspace for this project
- name: gcr.io/cloud-builders/kubectl
  args: ['set', 'image', 'deployment/match', 'match=gcr.io/cs3219-team23-328712/match:latest']
  env:
    - CLOUDSDK_COMPUTE_REGION=asia-southeast1-a
    - CLOUDSDK_CONTAINER_CLUSTER=peerup-cluster
    - KUBECONFIG=/workspace/.kube/config
    
# Deploy with Helm
- name: gcr.io/cloud-builders/kubectl
  args: ['helm', 'uninstall', 'peerup']
  env:
    - CLOUDSDK_COMPUTE_REGION=asia-southeast1-a
    - CLOUDSDK_CONTAINER_CLUSTER=peerup-cluster
    - KUBECONFIG=/workspace/.kube/config
    - TILLERLESS=false
    - TILLER_NAMESPACE=kube-system

# Delete all svc in kubectl
- name: gcr.io/cloud-builders/kubectl
  args: ['delete', 'svc', '--all']
  env:
    - CLOUDSDK_COMPUTE_REGION=asia-southeast1-a
    - CLOUDSDK_CONTAINER_CLUSTER=peerup-cluster
    - KUBECONFIG=/workspace/.kube/config

# Deploy with Helm
- name: gcr.io/cloud-builders/kubectl
  args: ['helm', 'install', 'peerup', 'helm-deployment/']
  env:
    - CLOUDSDK_COMPUTE_REGION=asia-southeast1-a
    - CLOUDSDK_CONTAINER_CLUSTER=peerup-cluster
    - KUBECONFIG=/workspace/.kube/config
    - TILLERLESS=false
    - TILLER_NAMESPACE=kube-system
images:
- gcr.io/cs3219-team23-328712/match:$COMMIT_SHA
options:
  logging: CLOUD_LOGGING_ONLY
