# cloudbuild.yaml

steps:
### Build & Deploy Match Microservice

# SERVICE_NAME = match
# IMAGE_NAME = match

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cs3219-team23-328712/match', './backend/match']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cs3219-team23-328712/match']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'match', '--image', 'gcr.io/cs3219-team23-328712/match', '--region', 'asia-east1']

- name: gcr.io/cloud-builders/kubectl
  id: Configure kubectl
  args:
    - cluster-info
  env:
    - CLOUDSDK_COMPUTE_REGION=asia-southeast1-a
    - CLOUDSDK_CONTAINER_CLUSTER=peerup-cluster
    - KUBECONFIG=/workspace/.kube/config

- name: gcr.io/cs3219-team23-328712/helm
  id: Deploy chart
  args:
    - upgrade
    - -i
    - peerprep
    - ./backend/helm-deployment
    # - -f
    # - ./backend/helm-deployment/values.yaml
  env:
    - KUBECONFIG=/workspace/.kube/config
    - TILLERLESS=true

# Set image of deployment match
# - name: gcr.io/cloud-builders/kubectl
#   args: ['set', 'image', 'deployment/match', 'match=gcr.io/cs3219-team23-328712/match:latest']
#   env:
#     - CLOUDSDK_COMPUTE_REGION=asia-southeast1-a
#     - CLOUDSDK_CONTAINER_CLUSTER=peerup-cluster
#     - KUBECONFIG=/workspace/.kube/config

#Uninstall with Helm
# - name: gcr.io/cs3219-team23-328712/helm
#   args: ['uninstall', 'peerprep']
#   env:
#     - KUBECONFIG=/workspace/.kube/config
#     - TILLERLESS=false
#     - TILLER_NAMESPACE=kube-system

# # Delete all svc in kubectl
# - name: gcr.io/cloud-builders/kubectl
#   args: ['delete', 'svc', '--all']
#   env:
#     - CLOUDSDK_COMPUTE_REGION=asia-southeast1-a
#     - CLOUDSDK_CONTAINER_CLUSTER=peerup-cluster
#     - KUBECONFIG=/workspace/.kube/config


# Deploy with Helm
# - name: gcr.io/cs3219-team23-328712/helm
#   args: ['install', 'peerprep', './backend/helm-deployment']
#   env:
#     - KUBECONFIG=/workspace/.kube/config
#     - TILLERLESS=false
#     - TILLER_NAMESPACE=kube-system

images:
- gcr.io/cs3219-team23-328712/match
options:
  logging: CLOUD_LOGGING_ONLY
