version: "3.9"
services:
  users:
    build: ./users
    ports:
      - "5001:5001"
  message:
    build: ./message
    ports:
      - "5002:5002"
  match:
      build: ./match
      ports:
        - "5003:5003"
      