version: "3"
services:
  users:
    image: users
    build: ./users
    ports:
      - "5001:5001"
  message:
    image: message
    build: ./message
    ports:
      - "5002:5002"
  editor:
    image: editor
    build: ./editor
    ports:
      - "5002:5002"
  match:
      image: match
      build: ./match
      ports:
        - "5004:5004"
  questions:
      image: questions
      build: ./questions
      ports:
        - "5005:5005"
      

# required to rebuild yaml files with helm 