service:
  type: ClusterIP
  
ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"     
  namespace: default
  path: /match
  pathtype: Prefix

