# cloudbuild.yaml

steps:
### Build & Deploy Questions Microservice

# SERVICE_NAME = question
# IMAGE_NAME = question

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cs3219-team23-328712/question:$COMMIT_SHA', './backend/questions']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cs3219-team23-328712/question:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'question', '--image', 'gcr.io/cs3219-team23-328712/question:$COMMIT_SHA', '--region', 'asia-east1']
  
images:
- gcr.io/cs3219-team23-328712/question:$COMMIT_SHA
options:
  logging: CLOUD_LOGGING_ONLY
